import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "MAMG Team T-Shirt",
    author: "Merdeces",
    price: "4500",
    categoryName: "Clothes",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539121/Products%20Images/Clothes/clothes-MAMG.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "25",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "RBR Team T-Shirt",
    author: "RedBall",
    price: "2500",
    categoryName: "Clothes",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539145/Products%20Images/Clothes/clothes-RBR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "10",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "AT Team T-Shirt",
    author: "Alpha-Ball",
    price: "2200",
    categoryName: "Clothes",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539225/Products%20Images/Clothes/clothes-AT.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "15",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "AMR Team T-Shirt",
    author: "Anton Marten",
    price: "2700",
    categoryName: "Clothes",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539203/Products%20Images/Clothes/clothes-AMR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "5",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "SF Team T-Shirt",
    author: "Purrari",
    price: "3100",
    categoryName: "Clothes",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539178/Products%20Images/Clothes/clothes-SF.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "2",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "WR Team Mask",
    author: "Welleams",
    price: "1199",
    categoryName: "Masks",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538501/Products%20Images/Masks/masks-FWR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "20",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "AMR Team Mask",
    author: "Anton Marten",
    price: "1299",
    categoryName: "Masks",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538469/Products%20Images/Masks/masks-AMR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "10",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "MAMG Team Mask",
    author: "Merdeces",
    price: "999",
    categoryName: "Masks",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538429/Products%20Images/Masks/masks-MAMG.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "40",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "RBR Team Mask",
    author: "Red-Ball",
    price: "1099",
    categoryName: "Masks",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538188/Products%20Images/Masks/masks-RBR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "10",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "MCL Team Mask",
    author: "BcLaren",
    price: "1350",
    categoryName: "Masks",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538401/Products%20Images/Masks/masks-MCL.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "30",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "MCL Backpack",
    author: "BcLaren",
    price: "4550",
    categoryName: "Bags",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538910/Products%20Images/Bags/bags-MCL.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "10",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "SF Backpack",
    author: "Purrari",
    price: "5450",
    categoryName: "Bags",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538735/Products%20Images/Bags/bags-SF.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "5",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "AMR Trolley Bag",
    author: "Anton Marten",
    price: "6899",
    categoryName: "Bags",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538758/Products%20Images/Bags/bag-AMR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "20",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "BWTA Backpack",
    author: "Alpeene",
    price: "3750",
    categoryName: "Bags",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538631/Products%20Images/Bags/bags-BWTA.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "25",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "AT Backpack",
    author: "Alpha-Ball",
    price: "6025",
    categoryName: "Bags",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647538886/Products%20Images/Bags/bags-AT.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "15",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "SF Model Car",
    author: "Purrari",
    price: "7590",
    categoryName: "Models",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647537785/Products%20Images/Models/model-SF.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "30",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "MAMG Model Car",
    author: "Merdeces",
    price: "9550",
    categoryName: "Models",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647537859/Products%20Images/Models/models-MAMG.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "25",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "BWTA Model Car",
    author: "Alpeene",
    price: "7325",
    categoryName: "Models",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647536336/Products%20Images/Models/models-BWTA.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "33",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "MCL Model Car",
    author: "BcLaren",
    price: "8740",
    categoryName: "Models",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647536249/Products%20Images/Models/models-MCL.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "10",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "RBR Model Car",
    author: "Red-Ball",
    price: "7980",
    categoryName: "Models",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647537947/Products%20Images/Models/models-RBR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "12",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "RBR Headwear",
    author: "Red-Ball",
    price: "3290",
    categoryName: "Headwear",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539750/Products%20Images/Headwear/headwear-RBR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "5",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "MCL Headwear",
    author: "BcLaren",
    price: "2995",
    categoryName: "Headwear",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539638/Products%20Images/Headwear/headwear-MCL.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "12",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "SF Headwear",
    author: "Purrari",
    price: "3755",
    categoryName: "Headwear",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539722/Products%20Images/Headwear/headwear-SF.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "8",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "AMR Headwear",
    author: "Anton Marten",
    price: "2650",
    categoryName: "Headwear",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539693/Products%20Images/Headwear/headwear-AMR.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "17",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
  {
    _id: uuid(),
    title: "MAMG Headwear",
    author: "Merdeces",
    price: "3830",
    categoryName: "Headwear",
    productImage: "https://res.cloudinary.com/fueledup-ecom/image/upload/v1647539670/Products%20Images/Headwear/headwear-MAMG.webp",
    productDescription: "This comfortable Replica Team McLaren hoodie is a perfect outer layer for any McLaren fan. This lightweight and breathable hoodie is engineered to perform at the highest level.",
    productDiscount: "20",
    productRating: ((Math.random() * 4)+1).toFixed(1),
    fastDelivery: false,
    inStock: true
  },
];
